<?php

namespace Plugin\TPSBooking\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\TPSBooking\Entity\TPSBooking;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * TPSBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TPSBookingRepository extends AbstractRepository
{
    /**
     * TPSBookingRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, TPSBooking::class);
    }

    public function getList()
    {
        $bookings = $this->createQueryBuilder('b')
            ->orderBy('b.datetime', 'DESC')
            ->getQuery()
            ->getResult();
        return $bookings;
    }

}
